sonar.projectKey=fabrikk
sonar.projectName=fabrikk
sonar.host.url=http://localhost:9000
sonar.sources=cmd,internal
sonar.tests=internal
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/testdata/**
sonar.go.coverage.reportPaths=coverage.out
